import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, rmSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { tmpdir } from 'node:os';
import ExcelJS from 'exceljs';
import { emptyState, apply, generate, eligible, deletionPreview, selection, cellText } from '../lib/domain.js';
import { Store, validateBackup } from '../lib/store.js';
import { workbook } from '../lib/export.js';
const NOW='2026-09-20T12:00';
function fixture() {
  const s=emptyState();
  apply(s,'year',{name:'2026–2027',start:'2026-09-01',end:'2027-08-31',quarters:[{start:'2026-09-01',end:'2026-10-25'},{start:'2026-11-05',end:'2026-12-28'},{start:'2027-01-09',end:'2027-03-22'},{start:'2027-04-01',end:'2027-05-31'}]},NOW);
  apply(s,'class',{name:'5А',yearId:s.years[0].id},NOW);
  apply(s,'subject',{name:'Математика',classId:s.classes[0].id},NOW);
  apply(s,'students',{classId:s.classes[0].id,names:['Иванова Анна','Петров Иван'],start:'2026-09-01'},NOW);
  return s;
}
function addLesson(s,date='2026-09-21',start='09:00',end='09:45') {apply(s,'lesson',{journalId:s.journals[0].id,date,start,end,topic:'',homework:''},NOW);return s.lessons.at(-1);}
const template = s => ({name:'Математика — 5А',journalId:s.journals[0].id,start:'2026-09-01',end:'2026-10-15',slots:[{day:1,start:'09:00',end:'09:45'},{day:3,start:'10:00',end:'10:45'}]});
test('Weekly generation respects inclusive boundaries, weekday and stable occurrence IDs',()=>{const s=fixture();apply(s,'template',template(s),NOW);const t=s.templates[0];const lessons=generate(t);assert.deepEqual(lessons,generate(t));assert.equal(new Set(lessons.map(x=>x.id)).size,lessons.length);assert.ok(lessons.every(l=>l.date>=t.start&&l.date<=t.end&&[1,3].includes(new Date(l.date).getUTCDay())));assert.equal(lessons[0].date,'2026-09-02');assert.equal(lessons.at(-1).date,'2026-10-14');});
test('Overlapping lessons across different journals are rejected',()=>{const s=fixture();addLesson(s);apply(s,'subject',{classId:s.classes[0].id,name:'Русский язык'},NOW);assert.throws(()=>apply(s,'lesson',{journalId:s.journals[1].id,date:'2026-09-21',start:'09:30',end:'10:15'},NOW),/уже есть урок/);});
test('Two separate lessons on the same date remain independent',()=>{const s=fixture();const a=addLesson(s),b=addLesson(s,'2026-09-21','10:00','10:45');assert.notEqual(a.id,b.id);assert.equal(selection(s,{journalId:s.journals[0].id,start:a.date,end:a.date}).lessons.length,2);});
test('Marks and attendance are independent and can be cleared',()=>{const s=fixture(),l=addLesson(s),st=s.students[0];apply(s,'record',{lessonId:l.id,studentId:st.id,status:'present',grades:[5,4]},NOW);assert.equal(cellText(s,st,l),'5 4 П');apply(s,'record',{lessonId:l.id,studentId:st.id,status:'ill',grades:[]},NOW);assert.equal(cellText(s,st,l),'Б');apply(s,'record',{lessonId:l.id,studentId:st.id,status:'',grades:[]},NOW);assert.equal(cellText(s,st,l),'');assert.equal(s.attendance.length,0);});
test('Bulk attendance does not replace existing absence or grades',()=>{const s=fixture(),l=addLesson(s);apply(s,'record',{lessonId:l.id,studentId:s.students[0].id,status:'absent',grades:[4]},NOW);apply(s,'present',{id:l.id},NOW);assert.equal(cellText(s,s.students[0],l),'4 Н');assert.equal(cellText(s,s.students[1],l),'П');});
test('Excluding a student preserves template, other students, and old records',()=>{const s=fixture();apply(s,'template',template(s),NOW);const past=s.lessons.find(l=>l.date<'2026-09-20'),future=s.lessons.find(l=>l.date>'2026-09-20');apply(s,'record',{lessonId:past.id,studentId:s.students[0].id,status:'present',grades:[5]},NOW);apply(s,'exclude',{templateId:s.templates[0].id,studentId:s.students[0].id,end:'2026-09-20'},NOW);assert.ok(s.templates[0].active);assert.ok(eligible(s,s.students[0],past));assert.ok(!eligible(s,s.students[0],future));assert.ok(eligible(s,s.students[1],future));assert.equal(cellText(s,s.students[0],past),'5 П');assert.throws(()=>apply(s,'record',{lessonId:future.id,studentId:s.students[0].id,status:'absent',grades:[]},NOW),/не участвует/);});
test('Deleting recurrence keeps history and future topics, homework, marks and attendance',()=>{const s=fixture();apply(s,'template',template(s),NOW);const t=s.templates[0],future=s.lessons.filter(l=>l.date>'2026-09-20');future[0].topic='Тема';future[1].homework='ДЗ';apply(s,'record',{lessonId:future[2].id,studentId:s.students[0].id,status:'',grades:[5]},NOW);apply(s,'record',{lessonId:future[3].id,studentId:s.students[0].id,status:'ill',grades:[]},NOW);const past=s.lessons.filter(l=>l.date<'2026-09-20').length;const preview=deletionPreview(s,t.id,NOW);assert.equal(preview.kept,past+4);assert.equal(preview.removed,future.length-4);apply(s,'deleteTemplate',{id:t.id},NOW);assert.equal(s.lessons.length,past+4);assert.ok(s.lessons.every(l=>l.templateId===null&&l.seriesId===t.id));assert.equal(s.students.length,2);assert.equal(s.templates[0].active,false);});
test('Month and quarter views reference the same lessons including boundaries',()=>{const s=fixture();addLesson(s,'2026-09-30');addLesson(s,'2026-10-01');addLesson(s,'2026-10-25');addLesson(s,'2026-10-26');const q=selection(s,{journalId:s.journals[0].id,...s.years[0].quarters[0]});const m=selection(s,{journalId:s.journals[0].id,start:'2026-09-01',end:'2026-09-30'});assert.equal(q.lessons.length,3);assert.equal(m.lessons.length,1);assert.equal(m.lessons[0],q.lessons[0]);});
test('School quarters cannot overlap',()=>{const s=fixture(),y=s.years[0];assert.throws(()=>apply(s,'year',{...y,quarters:y.quarters.map((q,i)=>i===1?{...q,start:'2026-10-20'}:q)},NOW),/не пересекаться/);});
test('Late joiners and archived pupils do not get automatic absences',()=>{const s=fixture();apply(s,'students',{classId:s.classes[0].id,names:['Новиков Алексей'],start:'2026-10-01'},NOW);const l=addLesson(s);assert.equal(cellText(s,s.students.at(-1),l),'Не участвует');apply(s,'archive',{id:s.students[0].id,end:'2026-09-21'},NOW);apply(s,'present',{id:l.id},NOW);assert.equal(s.attendance.length,1);});
test('Identical names have independent identities',()=>{const s=fixture();apply(s,'students',{classId:s.classes[0].id,names:['Иванова Анна'],start:'2026-09-01'},NOW);assert.notEqual(s.students[0].id,s.students[2].id);});
test('Invalid dates, grades and times are rejected',()=>{const s=fixture();assert.throws(()=>addLesson(s,'2026-02-30'));assert.throws(()=>addLesson(s,'2026-09-21','10:00','09:00'));const l=addLesson(s);assert.throws(()=>apply(s,'record',{studentId:s.students[0].id,lessonId:l.id,status:'present',grades:[0]},NOW));});
test('SQLite survives restart and rejects stale writes atomically',()=>{const dir=mkdtempSync(join(tmpdir(),'journal-store-'));try{let store=new Store(dir);const f=fixture();store.db.exec('BEGIN');store.save(f);store.db.exec('COMMIT');const before=store.state();assert.throws(()=>store.mutate('students',{classId:f.classes[0].id,names:['Тест'],start:'2026-09-01'},0),e=>e.status===409);assert.deepEqual(store.state(),before);assert.throws(()=>store.mutate('students',{classId:f.classes[0].id,names:['Сохранить нельзя',''],start:'2026-09-01'},before.revision));assert.deepEqual(store.state(),before);store.close();store=new Store(dir);assert.deepEqual(store.state(),before);store.close();}finally{rmSync(dir,{recursive:true,force:true});}});
test('Full backup restore validates references and preserves records',()=>{const dir=mkdtempSync(join(tmpdir(),'journal-backup-'));try{const store=new Store(dir);const s=fixture(),l=addLesson(s);apply(s,'record',{lessonId:l.id,studentId:s.students[0].id,status:'present',grades:[5]},NOW);const backup={format:'teacher-journal',version:1,state:{...s,timezone:'Europe/Moscow'}};store.restore(backup,0);assert.equal(store.state().grades[0].value,5);const bad=structuredClone(backup);bad.state.grades[0].lessonId='missing';assert.throws(()=>validateBackup(bad));assert.throws(()=>store.restore(bad,1));assert.equal(store.state().grades.length,1);store.close();}finally{rmSync(dir,{recursive:true,force:true});}});
test('XLSX contains all lessons, multiple marks and literal formula-like text',async()=>{const s=fixture();apply(s,'students',{classId:s.classes[0].id,names:['=HYPERLINK("https://example.invalid")'],start:'2026-09-01'},NOW);const l=addLesson(s);l.topic='=1+1';l.homework='Длинное домашнее задание';apply(s,'record',{lessonId:l.id,studentId:s.students[0].id,status:'present',grades:[5,4]},NOW);const buffer=await workbook(s,{journalId:s.journals[0].id,start:'2026-09-01',end:'2026-09-30'});const book=new ExcelJS.Workbook();await book.xlsx.load(buffer);assert.equal(book.worksheets.length,2);const content=book.getWorksheet('Уроки');assert.equal(content.getCell('C2').value,'=1+1');assert.equal(content.getCell('C2').type,ExcelJS.ValueType.String);const table=book.getWorksheet('Журнал');assert.ok(table.getSheetValues().flat(2).includes('5 4 П'));assert.ok(table.getSheetValues().flat(2).includes('=HYPERLINK("https://example.invalid")'));assert.equal(table.views[0].state,'frozen');});
